app:
  build: .
  volumes:
    - ./code:/app
  ports:
    - '8000:8000'
  environment:
    CODECLIMATE_REPO_TOKEN:
    SECRET_TOKEN:
    LASTFM_ID:
    LASTFM_SECRET:
    WORKER_PROCESSES:
    CACHE_URL:
    JOB_WORKER_URL:
    LISTEN_ON:
    DATABASE_URL:
sidekiq:
  build: .
  command: bundle exec sidekiq -C code/config/sidekiq.yml
  volumes:
    - ./code:/app
