version: '2'
volumes:
  tipjar-redis:
  tipjar-postgres:

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      # set these values in CI
      CODECLIMATE_REPO_TOKEN:
      SECRET_TOKEN:
      LASTFM_ID:
      LASTFM_SECRET:
      WORKER_PROCESSES: 1
      JWT_SECRET: replace-me
      SIDEKIQ_USERNAME: admin
      SIDEKIQ_PASSWORD: password123
      APP_ROOT: http://127.0.0.1:3000
      CACHE_URL: redis://redis:6379/0
      JOB_WORKER_URL: redis://redis:6379/0
      LISTEN_ON: 0.0.0.0:8000
      DATABASE_URL: postgresql://tipjar:yourpassword@postgres:5432/tipjar?encoding=utf8&pool=5&timeout=5000
    links:
      - postgres
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C code/config/sidekiq.yml
    links:
      - postgres
      - redis

  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: tipjar
      POSTGRES_PASSWORD: yourpassword

  redis:
    image: redis:3.0.5
