postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: tipjar
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5432:5432'
  volumes:
    - tipjar-postgres:/var/lib/postgresql/data

redis:
  image: redis:3.0.5
  ports:
    - '6379:6379'
  volumes:
    - tipjar-redis:/var/lib/redis/data

app:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - ./code:/app
  ports:
    - '8000:8000'
  env_file:
    - .docker.env

sidekiq:
  build: .
  command: bundle exec sidekiq -C code/config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - ./code:/app
  env_file:
    - .docker.env
