source 'https://rubygems.org'
ruby '2.2.5'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sidekiq'
gem 'sidekiq-throttler'
gem 'redis-rails'
gem 'unicorn'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'materialize-sass'

gem 'devise', '~> 3.5.1'
# gem 'omniauth-lastfm', '~> 0.0.7', git: "git://github.com/erikdstock/omniauth-lastfm.git"
gem 'omniauth-lastfm', '~> 0.0.6'
gem 'rest-client'

gem 'web-console', '~> 2.0', group: :development

gem 'codeclimate-test-reporter', group: :test, require: nil
gem 'vcr', group: :test
gem 'webmock', group: :test

group :development, :test do
  gem 'factory_girl_rails', "~> 4.0"
  gem 'faker'
  gem 'jasmine-rails'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'byebug'
  gem 'awesome_print'
  gem 'spring'
end

group :test do
  gem 'shoulda-matchers', '~> 3.1'
  gem 'launchy', '~> 2.4', '>= 2.4.3'
end
