source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.0.beta1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', github: "rails/sass-rails"

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', github: "rails/webpacker"

# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# App-specific dependencies
# gem 'unicorn' # Not using unicorn.
gem 'sidekiq'
gem 'sidekiq-throttler'
gem 'redis-rails'

gem 'devise'
gem 'devise-jwt', '~> 0.1.1'
gem 'omniauth-lastfm', '~>0.0.7' # Lastfm omniauth
# gem 'oauth' # I dont think this is needed. 


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.7.0'
  gem 'faker'
  gem 'selenium-webdriver'
  gem 'awesome_print'
  gem 'rspec-rails'
end
group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers', '~> 3.1'
  gem 'launchy', '~> 2.4', '>= 2.4.3'
  gem 'jasmine-rails'
  gem 'factory_girl_rails', "~> 4.0"
  gem 'vcr', group: :test
  gem 'webmock', group: :test
  gem 'simplecov', :require => false, :group => :test
  gem 'codeclimate-test-reporter', group: :test, require: nil

end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


### Copied from tipjar
# gem 'devise'
# # gem 'omniauth-lastfm', '0.0.7', github: "erikdstock/omniauth-lastfm"
# gem 'omniauth-lastfm', '~> 0.0.7'
# gem 'rest-client'

# # React client auth...
# gem 'oauth'
# gem 'jwt'

# gem 'vcr', group: :test
# gem 'webmock', group: :test
# gem 'simplecov', :require => false, :group => :test
# gem 'codeclimate-test-reporter', group: :test, require: nil

# group :development, :test do
# end

# group :test do
# end